name: tumbas
description: tumbas mawon

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod

